services:
  api:
    command: pnpm run dev
    ports:
      - "3001:3001"
    volumes:
      - ./todo-api:/app/todo-api
      - /app/node_modules
    env_file:
      - ./todo-api/.env.dev

  db:
    ports:
      - "3306:3306"
    env_file:
      - ./todo-api/.env.dev
    volumes:
      - db-data-dev:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d

volumes:
  db-data-dev:

  web:
    command: pnpm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./todo-web:/app/todo-web
      - /app/node_modules
