services:
  api:
    build:
      context: .
      dockerfile: ./todo-api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: ./todo-web/Dockerfile
    depends_on:
      - api

  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

