services:
  api:
    build: 
      context: .
      dockerfile: ./todo-api/Dockerfile
    depends_on:
      - db

  web:
    build: 
      context: .
      dockerfile: ./todo-web/Dockerfile
    depends_on:
      - api

  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./todo-api/.env.dev

volumes:
  db-data:

